mutation CheckoutLinesUpdate($checkoutId: ID!, $lines: [CheckoutLineUpdateInput!]!) {
	checkoutLinesUpdate(id: $checkoutId, lines: $lines) {
		checkout {
			id
			channel {
				slug
			}
			lines {
				id
				quantity
				totalPrice {
					net {
						amount
						currency
					}
					gross {
						amount
						currency
					}
				}
			}
			totalPrice {
				net {
					amount
					currency
				}
				gross {
					amount
					currency
				}
				tax {
					amount
					currency
				}
			}
		}
		errors {
			field
			message
			code
		}
	}
}
