fragment OrderDetails on Order {
	id
	number
	created
	# Decide si la orden se muestra en neto (canal B2B) o con IVA.
	channel {
		slug
	}
	total {
		net {
			amount
			currency
		}
		gross {
			amount
			currency
		}
		tax {
			amount
			currency
		}
	}
	lines {
		variant {
			id
			name
			translation(languageCode: $languageCode) {
				name
			}
			product {
				id
				name
				description
				slug
				translation(languageCode: $languageCode) {
					name
				}
				thumbnail {
					url
					alt
				}
				category {
					id
					name
				}
			}
			pricing {
				price {
					net {
						amount
						currency
					}
					gross {
						amount
						currency
					}
				}
			}
		}
		quantity
	}
	status
	statusDisplay
	paymentStatus
}
